# xxdk is built for this version of iOS or higher.
platform :ios, '17.0'

# This is required for Swift since it does not support static libraries.
use_frameworks!

target 'iOSExample' do
  # Use local XXDK (path should be the folder that contains the .podspec)
  pod 'XXDK', :path => '/Users/ommore/Documents/github/xx-network/client'

  pod 'Kronos'
end
